### ISSUE TITLE
KeyError: 'QueryInst is not in the models registry'

### ISSUE THREAD

**Issue by lbq779660843** [hustvl/QueryInst#18]
你好，我尝试在win10上用自己的数据集进行训练，但是返回了如下错误。

训练命令:
`python tools/train.py configs/queryinst/queryinst_r50_fpn_1x_coco_scratch.py`
我把queryinst_r50_fpn_1x_coco_scratch.py中num_classes改为了我的数据集类别总数。

运行后出现下面问题:
**Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 161, in main
    test_cfg=cfg.get('test_cfg'))
  File "C:\Users\RTX3090\.conda\envs\open-mmlab\lib\site-packages\mmdet\models\builder.py", line 58, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "d:\lbq\code\swin_tsf\mmsegmentation-master\mmcv\mmcv\utils\registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "d:\lbq\code\swin_tsf\mmsegmentation-master\mmcv\mmcv\cnn\builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "d:\lbq\code\swin_tsf\mmsegmentation-master\mmcv\mmcv\utils\registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'QueryInst is not in the models registry'
**

**Comment by Yuxin-CV** [comment]
Hi @lbq779660843，感谢你对我们工作的关注。

我们没有在`windows`系统下测试过`QueryInst`的代码。但是看你的报错,我觉得也许和路径、环境的问题有关系。
我建议你跑一下`mmdet`的`Mask R-CNN`模型，看看能否跑通。

**Comment by dongdongyee** [comment]
作者您好！感谢分享优秀的工作。
我在linux上用自己的数据集进行训练，只更改了num_classes和数据路径，其他的config没用动，可以成功用tools/train.py 训练，但是测试时，
用python tools/test.py configs/queryinst/coco_v2.py output/epoch_31.pth --format-only --options "jsonfile_prefix=./output"命令，报错：

tools/test.py:96: UserWarning: --options is deprecated in favor of --eval-options
  warnings.warn('--options is deprecated in favor of --eval-options')
loading annotations into memory...
Done (t=0.21s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/test.py", line 220, in <module>
    main()
  File "tools/test.py", line 173, in main
    model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/search/odin/sdy/anaconda3/envs/mmcv/lib/python3.8/site-packages/mmdet/models/builder.py", line 57, in build_detector
    return DETECTORS.build(
  File "/search/odin/sdy/anaconda3/envs/mmcv/lib/python3.8/site-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/search/odin/sdy/anaconda3/envs/mmcv/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/search/odin/sdy/anaconda3/envs/mmcv/lib/python3.8/site-packages/mmcv/utils/registry.py", line 43, in build_from_cfg
    raise KeyError(
KeyError: 'QueryInst is not in the models registry'

**Comment by lbq779660843** [comment]
我在windows平台上跑通了，相关细节可以参考https://blog.csdn.net/qq_33642342/article/details/119028324?spm=1001.2014.3001.5501。
I’ve successfully trained the model on the wiondows and the relevant details are recorded in my blog https://blog.csdn.net/qq_33642342/article/details/119028324?spm=1001.2014.3001.5501.
